---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: child-apply
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./config/child/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: child-kubeconfig
  timeout: 2m
